### ISSUE TITLE
help

### ISSUE THREAD

**Issue by om3ga6400** [irwintech/about-blank-cloak-for-tab#1]
So, if i wanted to make a website that as soon as you visit it, it opens another website in a about:blank tab how would i do it? @irwintech

**Comment by om3ga6400** [comment]
like if i open a site it automatically redirect to about blank

**Comment by JaydenWong69** [comment]
same issue here

**Comment by om3ga6400** [comment]
@JaydenWong69 i figured out how to do it but for some reason it only works on chrome book

**Comment by JaydenWong69** [comment]
oh ok
